#!/bin/bash

# VS Code Extension Installation Script
# Generated by Antigravity

extensions=(
  "bradlc.vscode-tailwindcss"
  "dbaeumer.vscode-eslint"
  "eamodio.gitlens"
  "esbenp.prettier-vscode"
  "formulahendry.auto-rename-tag"
  "ms-azuretools.vscode-containers"
  "ms-vscode-remote.remote-containers"
  "pkief.material-icon-theme"
  "ritwickdey.liveserver"
  "rodrigovallades.es7-react-js-snippets"
)

echo "Installing VS Code extensions..."

for extension in "${extensions[@]}"
do
  echo "Installing $extension..."
  code --install-extension "$extension"
done

echo "All extensions installed!"
